### ISSUE TITLE
Regular expression to find flanking region

### ISSUE THREAD

**Issue by giriarteS** [indraniel/fqgrep#2]
I am trying to locate the primers in a large fasta file. I have been using grep but I want to allow mismatches. I can I use this with fqgrep?
grep --color -B1 "TCGATGAAGAACGCAGCG[A-Z]*GCATATCAATAAGCGGA" seq.fasta

**Comment by indraniel** [comment]
Apologies about the delayed reply.  But I think that should have worked.
